### ISSUE TITLE
Add Security Samples - PKI

### ISSUE THREAD

**Issue by ThadT** [Esri/arcgis-runtime-samples-dotnet#157]
Update the 10.2.7 PKI security sample for Quartz.
- [x] WPF (CS) PR #233 ready for review
- [x] WPF (VB) PR #233 ready for review
- [x] UWP (CS) PR #231 ready for review
- [x] UWP (VB) PR #231 ready for review

**Comment by ThadT** [comment]
I've completed these samples, but cannot successfully connect to my test portal using a client certificate. I need to troubleshoot more and see if the problem is with my code on the server.

**Comment by ThadT** [comment]
WPF and UWP versions are complete (C# and VB)
