### ISSUE TITLE
Add solution code for 'author, edit, and save map ...' tutorial

### ISSUE THREAD

**Issue by ThadT** [Esri/arcgis-runtime-samples-dotnet#220]
The guide doc tutorial is pretty long and it'd be nice if the completed code were available. This needs to be done for all platforms.

 - [x] WPF: Pull request #222 has been merged
 - [x] UWP: Pull request #219 has been merged
 - [x] Android Pull request #226 has been merged
 - [x] iOS: Pull request #228 ready for review
 - [x] Xamarin.Forms: Pull request #229 ready for review
